security:
    encoders:
        hsTrading\FrontEndBundle\Security\WebServiceUser:
            algorithm:        md5
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN

    providers:
        webservice_user:
            id: webservice_user_provider

    firewalls:
        login:
            pattern:  ^/login$
            security: false
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|favicon.ico|ico)/
            security: false
        secured_area:
            pattern: ^/
            anonymous: ~
            logout:
                path:   /logout
                target: /home
            form_login:
                login_path: /login
                check_path:  /login_check
                username_parameter: login[login]
                password_parameter: login[password]
                csrf_parameter: login[_token]
                csrf_provider: form.csrf_provider
                provider: webservice_user
                intention: authentication
                # On success
                always_use_default_target_path: true
                default_target_path: admin_panel

    access_control:
         - { path: ^/admin_panel, roles: ROLE_ADMIN }
         - { path: ^/contacts_history, roles: ROLE_ADMIN }
         - { path: ^/contacts, roles: ROLE_ADMIN }
         - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
