Home:
    resource: "@hsTradingFrontEndBundle/Controller/HomeController.php"
    type:     annotation
Base:
    resource: "@hsTradingFrontEndBundle/Controller/BaseIhmController.php"
    type:     annotation
