Home:
    resource: "@hsTradingFrontEndBundle/Controller/HomeController.php"
    type:     annotation
Base:
    resource: "@hsTradingFrontEndBundle/Controller/BaseIhmController.php"
    type:     annotation
Security:
    resource: "@hsTradingFrontEndBundle/Controller/SecurityController.php"
    type:     annotation
Admin:
    resource: "@hsTradingFrontEndBundle/Controller/AdminController.php"
    type:     annotation
ContactHistory:
    resource: "@hsTradingFrontEndBundle/Controller/ContactController.php"
    type:     annotation
Categories:
    resource: "@hsTradingFrontEndBundle/Controller/CategoriesController.php"
    type:     annotation
