parameters:
    webservice_user_provider.class: hsTrading\FrontEndBundle\Security\WebServiceUserProvider
    dataService.class: hsTrading\FrontEndBundle\Services\DataService
    mailService.class: hsTrading\FrontEndBundle\Services\MailService
    locale_listener.class: hsTrading\FrontEndBundle\Listener\LocaleListener
    LogoutListener.class: MY\StaticBundle\Service\LogoutListenerService
    file.img_extensions: [ png, jpeg, jpg]
    file.upload_base_dir: "%kernel.root_dir%/../web/tmp"
    IEService.class: hsTrading\FrontEndBundle\Services\IEService

services:
    
    webservice_user_provider:
        class: %webservice_user_provider.class%
        arguments: [@service_container]
        
    dataService:
        class: %dataService.class%
        arguments: [@service_container]
        
    mailService:
        class: %mailService.class%
        arguments: [@service_container]
        
    mail_logger:
        class: Symfony\Bridge\Monolog\Logger
        arguments: [mail]
        calls:
            - [pushHandler, [@mail_handler]]
            
    mail_handler:
        class: Monolog\Handler\RotatingFileHandler
        arguments: [%kernel.logs_dir%/%kernel.environment%.mailer.log, 10] 
    
    locale_listener:
        class: %locale_listener.class%
        arguments: ["%kernel.default_locale%"]
        tags:
         - { name: kernel.event_subscriber , event: kernel.request, method: setLocale, priority: 17}
         
    IEService:
        class: "%IEService.class%"
        arguments: [ "@service_container" ]