parameters:
    webservice_user_provider.class: hsTrading\FrontEndBundle\Security\WebServiceUserProvider

services:
    webservice_user_provider:
        class: %webservice_user_provider.class%
        arguments: [@service_container]