parameters:
#    hs_trading_front_end.example.class: hsTrading\FrontEndBundle\Example

services:
#    hs_trading_front_end.example:
#        class: %hs_trading_front_end.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
