parameters:
    max_allowed_amount_b2c: 4
    max_allowed_amount_b2b: null
    num_affiliation: '0870064011'
    page: 1
    max_per_page: 10
    wg_max_per_page: 6
    type: b2b
    ticketstatus: ticket
    treatedType: client
    jtable.columns:
        products:
            options: ~
            fields:
                id:
                    htmlOptions:
                        data-identifier: "true"
                        data-visible : "false"
                        data-visible-in-selection: "false"
                code:
                    width: 20%
                    htmlOptions:
                        data-identifier: "true"
                        data-visible : "false"
                        data-visible-in-selection: "false"
                category:
                    width: 10%
                    list: true
                designation:
                    width: 15%
                    list: true
                description:
                    list: true
                    width: 15%
                    sorting: true
                price:
                    width: 30%
                    list: true
                img:
                    width: 30%
                    list: true
                    htmlOptions:
                        data-formatter: pix
                action_edit:
                    width: 10%
                    sorting: false
                    htmlOptions:
                        data-formatter: "action_edit"
                        data-sortable: "false"
                action_delete:
                    width: 10%
                    sorting: false
                    htmlOptions:
                        data-formatter: "action_delete"
                        data-sortable: "false"
        contacts:
            options: ~
            fields:
                id:
                    htmlOptions:
                        data-identifier: "true"
                        data-visible : "false"
                        data-visible-in-selection: "false"
                firstname:
                    width: 10%
                    list: true
                lastname:
                    width: 10%
                    list: true
                mail:
                    width: 10%
                    list: true
                phone:
                    width: 10%
                    list: true
                company:
                    width: 10%
                    list: true
                country:
                    width: 10%
                    list: true
                message:
                    width: 30%
                    list: true
                treated:
                    width: 10%
                    list: true
                action_edit:
                    width: 10%
                    sorting: false
                    htmlOptions:
                        data-formatter: "action_edit"
                        data-sortable: "false"
        categories:
            options: ~
            fields:
                id:
                    htmlOptions:
                        data-identifier: "true"
                        data-visible : "false"
                        data-visible-in-selection: "false"
                code:
                    width: 40%
                    list: true
                label:
                    width: 40%
                    list: true
                action_edit:
                    width: 10%
                    sorting: false
                    htmlOptions:
                        data-formatter: "action_edit"
                        data-sortable: "false"
                        data-width: "10%"
                action_delete:
                    width: 10%
                    sorting: false
                    htmlOptions:
                        data-formatter: "action_delete"
                        data-sortable: "false"
                        data-width: "10%"
        sub_categories:
            options: ~
            fields:
                id:
                    htmlOptions:
                        data-identifier: "true"
                        data-visible : "false"
                        data-visible-in-selection: "false"
                category_label:
                    width: 40%
                    list: true
                code:
                    width: 40%
                    list: true
                label:
                    width: 40%
                    list: true
                action_edit:
                    width: 10%
                    sorting: false
                    htmlOptions:
                        data-formatter: "action_edit"
                        data-sortable: "false"
                        data-width: "10%"
                action_delete:
                    width: 10%
                    sorting: false
                    htmlOptions:
                        data-formatter: "action_delete"
                        data-sortable: "false"
                        data-width: "10%"
                    

    messages.bootgrid:
        noResults: noResults
        pagination_info: pagination_info
        refresh: refresh
        loading: loading
        all: all
    messages.products:
        products_table_title: products_table_title
        dialog_title: dialog_title
        dialog_error_title: dialog_error_title
        add_product_dialog_title: add_product_dialog_title
        edit_product_dialog_title: edit_product_dialog_title
        error: error
        edit_record: edit_record
        confirmation: confirmation
        add_confirmation: add_confirmation
        edit_confirmation: edit_confirmation
        cancel_button: cancel_button
        button_add: save_button
        button_add_in_progress: button_add_in_progress
        erreur.message: erreur.message
        erreur_title: erreur.title
        enable_title: enable_title
        disable_title: disable_title
        delete_product_dialog_title: delete_product_dialog_title
    messages.contact:
        confirmation: confirmation
        close: close
        contact_confirmation_message: contact_confirmation_message
    