parameters:
    max_allowed_amount_b2c: 4
    max_allowed_amount_b2b: null
    num_affiliation: '0870064011'
    page: 1
    max_per_page: 10
    wg_max_per_page: 6
    type: b2b
    ticketstatus: ticket
    treatedType: client
    jtable.columns:
        order:
            options: ~
            fields:
                pk:
                    htmlOptions:
                        data-identifier: "true"
                        data-visible : "false"
                        data-visible-in-selection: "false"
                link:
                    width: 40%
                    sorting: true
                    htmlOptions:
#                         data-align: "center"
                         headerAlign: "center"
                amount:
                    width: 10%
                    sorting: true
                    htmlOptions:
#                        data-align: "center"
                description:
                    width: 30%
                    list: true
                action:
                    width: 10%
                    htmlOptions:
                        data-formatter: "commands"
                        data-sortable: "false"  
        product:
            options: ~
            fields:
                id:
                    key: true
                    create: false
                    edit: false
                    list: false
                link:
                    width: 60%
                    sorting: false
                    list: true
                amount:
                    width: 10%
                    list: true
                final_price:
                    width: 10%
                    sorting: false
                    list: true
#                id_unit_dest:
#                    width: 15%
#                    sorting: false
#                    list: true
                status_label:
                    width: 10%
                    sorting: false
                    list: true
                created_at:
                    list: false
                status_code:
                    list: false
                action:
                    width: 10%
                    list: true
        order_in_progress:
            options: ~
            fields:
                id:
                    key: true
                    create: false
                    edit: false
                    list: false
                code:
                    list: true
                    width: 40%
                    sorting: false
                    filtering:
                        type : text
                status:
                    width: 40%
                    list: true
                    filtering:
                        type : choice
                        src: get_status
                date_begin:
                    width: 20%
                    list: true
                    sorting: true
                    edit: false
                    create: false
                    filtering:
                        type : date
                        options:
                            widget : single_text
                date_end:
                    width: 30%
                    list: false
                    sorting: true
                    edit: false
                    create: false
                    filtering:
                        type : date
                        options:
                            widget : single_text
        order_history:
            options: ~
            fields:
                id:
                    key: true
                    create: false
                    edit: false
                    list: false
                code:
                    list: true
                    width: 20%
                    sorting: false
                    filtering:
                        type : text
                status:
                    width: 40%
                    list: true
                    filtering:
                        type : choice
                        src: get_status
                delivery_date:
                    width: 30%
                    list: true
                    sorting: true
                    edit: false
                    create: false
                    filtering:
                        type : date
                        options:
                            widget : single_text
                date_begin:
                    width: 30%
                    list: true
                    sorting: true
                    edit: false
                    create: false
                    filtering:
                        type : date
                        options:
                            widget : single_text
                date_end:
                    list: false
                    sorting: true
                    edit: false
                    create: false
                    filtering:
                        type : date
                        options:
                            widget : single_text
        products:
            options: ~
            fields:
                code:
                    width: 20%
                    htmlOptions:
                        data-identifier: "true"
                        data-visible : "false"
                        data-visible-in-selection: "false"
                category:
                    width: 10%
                    list: true
                description:
                    list: true
                    width: 15%
                    sorting: true
                designation:
                    width: 15%
                    list: true
                price:
                    width: 30%
                    list: true
                img:
                    width: 30%
                    list: true
                    htmlOptions:
                        data-formatter: pix
                    
        ticket:
           options: ~
           fields:
                code:
                    width: 20%
                    htmlOptions:
                        data-identifier: "true"
                        data-visible : "false"
                        data-visible-in-selection: "false"
                order_code:
                    width: 10%
                    htmlOptions:
                        data-sortable: "true"
                        data-formatter: "linkOrder"
                product_code:
                    width: 10%
                    htmlOptions:
                        data-sortable: "true"
                        data-formatter: "linkOrder"
                category_label:
                    width: 20%
                    htmlOptions:
                        data-sortable: "true"
                status_label:
                    width: 10%
                    list: true
                    htmlOptions:
                        data-sortable: "true"
                    filtering:
                        type : choice
                        src: get_status
                created_at:
                    width: 15%
                    htmlOptions:
                        data-formatter: "dateFormat"
                        data-sortable: "true"
                        data-order: "desc"
                action:
                    width: 20%
                    sorting: false
                    htmlOptions:
                        data-formatter: "commands"
                        data-sortable: "false"
        frontal_ticket:
            options: ~
            fields:
                code:
                    width: 10%
                    htmlOptions:
                        data-identifier: "true"
                        data-visible : "false"
                        data-visible-in-selection: "false"
                order_code:
                    width: 10%
                    htmlOptions:
                        data-sortable: "true"
                        data-formatter: "linkOrder"
                product_code:
                    width: 10%
                    htmlOptions:
                        data-sortable: "true"
                        data-formatter: "linkOrder"
                category_label:
                    width: 20%
                    htmlOptions:
                        data-sortable: "true"
                status_label:
                    width: 10%
                    htmlOptions:
                        data-sortable: "true"
                    filtering:
                        type : choice
                        src: get_status
                created_at:
                    width: 15%
                    htmlOptions:
                        data-formatter: "dateFormat"
                        data-sortable: "true"
                        data-order: "desc"
                action:
                    width: 15%
                    sorting: false
                    htmlOptions:
                        data-formatter: "commands"
                        data-sortable: "false"
        ticket_message:
            options: ~
            fields:
                code:
                    width: 10%
                    htmlOptions:
                        data-identifier: "true"
                        data-sortable: "f"
                        data-visible : "false"
                        data-visible-in-selection: "false"
                message:
                    width: 15%
                    htmlOptions:
                        data-sortable: "true"
                        data-formatter: "text"
                created_at:
                    width: 15%
                    htmlOptions:
                        data-formatter: "dateFormat"
                        data-sortable: "true"
                        data-order: "desc"
        permanent.order:
            options: ~
            fields:
                id:
                    key: true
                    create: false
                    edit: false
                    list: false
                code:
                    list: true
                    width: 40%
                    sorting: false
                    filtering:
                        type : text
                status:
                    width: 40%
                    list: true
                    filtering:
                        type : choice
                        src: get_status
                date_begin_abn:
                    width: 20%
                    list: true
                    sorting: true
                    edit: false
                    create: false
                    filtering:
                        type : date
                        options:
                            widget : single_text
                date_end:
                    width: 30%
                    list: false
                    sorting: true
                    edit: false
                    create: false
                    filtering:
                        type : date
                        options:
                            widget : single_text

    messages.bootgrid:
        noResults: noResults
        pagination_info: pagination_info
        refresh: refresh
        loading: loading
        all: all
    messages.orders:
        suborder_List_title: suborder_List_title
        order_table_title: order_table_title
        dialog_title: dialog_title
        dialog_error_title: dialog_error_title
        erreur_message: erreur_message
        erreur_title: erreur_title
        button_add: add_button
        button_add_in_progress: button_add_in_progress
        alert_title: alert_title
        alert_message: alert_message
        error: error
        edit_record: edit_record
        preview_record: preview_record
        cancel_record: cancel_button
        cancel_product_confirm: cancel_product_confirm
        delete_product_confirm: delete_product_confirm
        button_delete: button_delete
        dialog_delete_title: dialog_delete_title
        delete_progress_message: delete_progress_message
        confirmation_title: confirmation_title
        confirmation_ticket_content: confirmation_ticket_content
        confirmation_ticket_message_content: confirmation_ticket_message_content
        erreur.message: erreur.message
        erreur.title: erreur.title
        delete_order_confirm: delete_order_confirm
        delete_permanent_order_confirm: delete_permanent_order_confirm
        cancel_order_confirm: cancel_order_confirm
        confirmation: confirmation
        confirm_success_message: confirm_success_message
        cancel_success_message: cancel_success_message
        delete_success_message: delete_success_message
        confirm_permanent_success_message: confirm_permanent_success_message
        cancel_permanent_success_message: cancel_permanent_success_message
        cancel_product_success_message: cancel_product_success_message
        delete_product_success_message: delete_product_success_message
        add_product_title: add_product
        add_confirm: add_confirm
        empty_basket_confirm: empty_basket_confirm
        confirm_close_ticket: confirm_close_ticket
        confirm_hide_ticket: confirm_hide_ticket
        confirm_order_confirm:  confirm_order_confirm
        confirm_permanentorder_confirm:  confirm_permanentorder_confirm
        cancel_permanentorder_confirm:  cancel_permanentorder_confirm
        product_scroll_details: product_scroll_details
        button_save_inprogress: button_save_inprogress
        button_save: button_save
        update_product_title: update_product_title
        update_product_success: update_product_success
        ticket_title_msg: ticket_title_msg
        edit_progress_message: edit_progress_message
        update_button: update_button
        ticket_info: ticket_info
        action_info: action_info
        message_action_info: message_action_info
        save_order_confirm: save_order_confirm
        dialog_add_message_title: dialog_add_message_title
        delete_basket: delete_basket
        complete_order: complete_order
        add_product: add_product
        add_ticket_message: add_ticket_message
        add_ticket: add_ticket

    messages.users:
        user_table_title: user_table_title
        dialog_title: dialog_title
        dialog_error_title: dialog_error_title
        add_user_dialog_title: add_user_dialog_title
        edit_user_dialog_title: edit_user_dialog_title
        error: error
        edit_record: edit_record
        confirmation: confirmation
        add_confirmation: add_confirmation
        edit_confirmation: edit_confirmation
        cancel_button: cancel_button
        button_add: save_button
        button_add_in_progress: button_add_in_progress
        erreur.message: erreur.message
        erreur_title: erreur.title
        enable_title: enable_title
        disable_title: disable_title

    messages.address:
        confirmation_title: confirmation_title
        cancel_button: cancel_button
        erreur_message: erreur.message
        erreur_title: erreur_title

        add_title: add_title
        add_button: add_button
        add_button_inprogress: add_button_inprogress
        add_confirm: added_address

        update_title: update_title
        update_button: update_button
        update_button_inprogress: edit_progress_message
        update_confirm: updated_address

        delete_title: delete_title
        delete_button: delete_button
        delete_button_inprogress: delete_button_inprogress
        delete_content: delete_content
        delete_success_message_address: delete_success_message_address
    messages.password:
        confirm: confirm_title
        close: close
        send:
            title_reset: title_reset
            cancel: cancel
            button_send: send
            button_inprogress_send: send_inprogress

    messages.profile:
        update_button_inprogress: edit_progress_message
        update_button: Modifier
        confirmation: confirmation
        update_confirmation_message: update_confirmation_message
        close: close
    
    messages.subscription:
        cgu: cgu
        cgv: cgv
        close: close
        confirmation_title: confirmation
        confirmation_message: confirmation_message
        
    messages.contact:
        confirmation: confirmation
        close: close
        contact_confirmation_message: contact_confirmation_message
